site_name: Py-RPAutom
dev_addr: localhost:9999
repo_url: https://github.com/arumeidaaran/py-rpautom
repo_name: py-rpautom
remote_branch: gh-pages
remote_name: origin

watch:
  - docs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["py_rpautom"]
          options:
            docstring_style: google
            docstring_options:
              returns_multiple_items: false
  - search

hooks:
  - docs/hooks/formatting.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

nav:
  - Início: index.md
  - Breve história: historia.md
  - Dependências do projeto: dependencias.md
  - Guia de automação web: guia_usuario/web_utils.md
  - Guia de automação desktop: guia_usuario/desktop_utils.md
  - Guia de utilitários python: guia_usuario/python_utils.md
  - Sobre:
    - Notas de versão: sobre/notas-versao.md
    - Licença: sobre/license.md
